version: '3.8'
services:
  ngelakoni-db:
    image: postgres:latest
    container_name: ngelakoni-db
    environment:
      - POSTGRES_DB=ngelakoni_app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=naufal
    ports:
      - 5434:5432
    volumes:
      - ngelakoni-volume:/var/lib/postgresql/data
    networks:
      ngelakoni-network:
        aliases:
          - postgres
    restart: always

  ngelakoni-app:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: ngelakoni-app
    ports:
      - 5000:5000
    volumes:
      - ./flask:/flask-app # Bind mount
    environment:
      - DB_HOST=ngelakoni-db
      - DB_PORT=5432
      - DB_NAME=ngelakoni_app
      - DB_USER=postgres
      - DB_PASSWORD=naufal
    depends_on:
      - ngelakoni-db
    networks:
      - ngelakoni-network
    restart: always

networks:
  ngelakoni-network:
    name: ngelakoni-network

volumes:
  ngelakoni-volume:
    name: ngelakoni-volume